---
permalink: sg6000/configuring-bmc-interface-sg6000.html
sidebar: sidebar
keywords: storagegrid, sg6000, sg6000-cn, storage node, storage appliance, BMC, baseboard management controller, configure, setup, set up
summary: 'The user interface for the baseboard management controller \(BMC\) on the SG6000-CN controller provides status information about the hardware and allows you to configure SNMP settings and other options for the SG6000-CN controller.'
---
= Configuring the BMC interface
:icons: font
:imagesdir: ../media/

[.lead]
The user interface for the baseboard management controller (BMC) on the SG6000-CN controller provides status information about the hardware and allows you to configure SNMP settings and other options for the SG6000-CN controller.

.Steps

* link:changing-root-password-for-bmc-interface-sg6000.html[Changing the root password for the BMC interface]
* link:setting-ip-address-for-bmc-management-port-sg6000.html[Setting the IP address for the BMC management port]
* link:accessing-bmc-interface-sg6000.html[Accessing the BMC interface]
* link:configuring-snmp-settings-for-sg6000-cn-controller.html[Configuring SNMP settings for the SG6000-CN controller]
* link:setting-up-email-notifications-for-alerts.html[Setting up email notifications for alerts]
