---
permalink: sg6000/configuring-storagegrid-connections.html
sidebar: sidebar
keywords: storagegrid, sg6000, storage node, storage appliance, storagegrid connections, connections, configure, setup, set up
summary: 'Before you can deploy a StorageGRID appliance as a Storage Node in a StorageGRID system, you must configure the connections between the appliance and the networks you plan to use. You can configure networking by browsing to the StorageGRID Appliance Installer, which is pre-installed on the SG6000-CN controller \(the compute controller\).'
---
= Configuring StorageGRID connections
:icons: font
:imagesdir: ../media/

[.lead]
Before you can deploy a StorageGRID appliance as a Storage Node in a StorageGRID system, you must configure the connections between the appliance and the networks you plan to use. You can configure networking by browsing to the StorageGRID Appliance Installer, which is pre-installed on the SG6000-CN controller (the compute controller).

.Steps

* link:accessing-storagegrid-appliance-installer-sg6000.html[Accessing the StorageGRID Appliance Installer]
* link:verifying-and-upgrading-storagegrid-appliance-installer-version.html[Verifying and upgrading the StorageGRID Appliance Installer version]
* link:configuring-network-links-sg6000.html[Configuring network links (SG6000)]
* link:configuring-storagegrid-ip-addresses-sg6000.html[Configuring StorageGRID IP addresses]
* link:verifying-network-connections.html[Verifying network connections]
* link:verifying-port-level-network-connections.html[Verifying port-level network connections]
