---
permalink: audit/client-write-audit-messages.html
sidebar: sidebar
keywords: storagegrid, audit, message, messages, client write, OVWR, SDEL, SPOS, SPUT, SUPD, WDEL, WPUT, S3, swift
summary: 'Client write audit messages are logged when an S3 or Swift client application makes a request to create or modify an object.'
---
= Client write audit messages
:icons: font
:imagesdir: ../media/

[.lead]
Client write audit messages are logged when an S3 or Swift client application makes a request to create or modify an object.

[options="header"]
|===
| Code| Description| Used by| See
a|
OVWR
a|
Object Overwrite: Logs a transaction to overwrite one object with another object.
a|
S3 clients

Swift clients

a|
link:ovwr-object-overwrite.html[OVWR: Object Overwrite]
a|
SDEL
a|
S3 DELETE: Logs a successful transaction to delete an object or bucket.

*Note:* If the transaction operates on a subresource, the audit message will include the field S3SR.

a|
S3 client
a|
link:sdel-s3-delete.html[SDEL: S3 DELETE]
a|
SPOS
a|
S3 POST: Logs a successful transaction to restore an object from AWS Glacier storage to a Cloud Storage Pool.
a|
S3 client
a|
link:spos-s3-post.html[SPOS: S3 POST]
a|
SPUT
a|
S3 PUT: Logs a successful transaction to create a new object or bucket.

*Note:* If the transaction operates on a subresource, the audit message will include the field S3SR.

a|
S3 client
a|
link:sput-s3-put.html[SPUT: S3 PUT]
a|
SUPD
a|
S3 Metadata Updated: Logs a successful transaction to update the metadata for an existing object or bucket.
a|
S3 client
a|
link:supd-s3-metadata-updated.html[SUPD: S3 Metadata Updated]
a|
WDEL
a|
Swift DELETE: Logs a successful transaction to delete an object or container.
a|
Swift client
a|
link:wdel-swift-delete.html[WDEL: Swift DELETE]
a|
WPUT
a|
Swift PUT: Logs a successful transaction to create a new object or container.
a|
Swift client
a|
link:wput-swift-put.html[WPUT: Swift PUT]
|===
