---
permalink: audit/system-audit-messages.html
sidebar: sidebar
keywords: storagegrid, audit, message, messages, system, ECOC, ETAF, GNRG, GNUR, GTED, GTST, GTSU, IDEL, LKCU, LLST, OLST, ORLM, SADD, SADE, SVRF, SVRU, SYSD, SYST, SYSU, VLST
summary: 'You should be familiar with audit messages belonging to the system audit category. These are events related to the auditing system itself, grid node states, system-wide task activity \(grid tasks\), and service backup operations, so that you can address potential issues.'
---
= System audit messages
:icons: font
:imagesdir: ../media/

[.lead]
You should be familiar with audit messages belonging to the system audit category. These are events related to the auditing system itself, grid node states, system-wide task activity (grid tasks), and service backup operations, so that you can address potential issues.

[options="header"]
|===
| Code| Message title and description| See
a|
ECOC
a|
Corrupt Erasure Coded Data Fragment: Indicates that a corrupt erasure coded data fragment has been detected.
a|
link:ecoc-corrupt-erasure-coded-data-fragment.html[ECOC: Corrupt Erasure Coded Data Fragment]
a|
ETAF
a|
Security Authentication Failed: A connection attempt using Transport Layer Security (TLS) failed.
a|
link:etaf-security-authentication-failed.html[ETAF: Security Authentication Failed]
a|
GNRG
a|
GNDS Registration: A service updated or registered information about itself in the StorageGRID system.
a|
link:gnrg-gnds-registration.html[GNRG: GNDS Registration]
a|
GNUR
a|
GNDS Unregistration: A service has unregistered itself from the StorageGRID system.
a|
link:gnur-gnds-unregistration.html[GNUR: GNDS Unregistration]
a|
GTED
a|
Grid Task Ended: The CMN service finished processing the grid task.
a|
link:gted-grid-task-ended.html[GTED: Grid Task Ended]
a|
GTST
a|
Grid Task Started: The CMN service started to process the grid task.
a|
link:gtst-grid-task-started.html[GTST: Grid Task Started]
a|
GTSU
a|
Grid Task Submitted: A grid task was submitted to the CMN service.
a|
link:gtsu-grid-task-submitted.html[GTSU: Grid Task Submitted]
a|
IDEL
a|
ILM Initiated Delete: This audit message is generated when ILM starts the process of deleting an object.
a|
link:idel-ilm-initiated-delete.html[IDEL: ILM Initiated Delete]
a|
LKCU
a|
Overwritten Object Cleanup. This audit message is generated when an overwritten object is automatically removed to free up storage space.
a|
link:lkcu-overwritten-object-cleanup.html[LKCU: Overwritten Object Cleanup]
a|
LLST
a|
Location Lost: This audit message is generated when a location is lost.
a|
link:llst-location-lost.html[LLST: Location Lost]
a|
OLST
a|
Object Lost: A requested object cannot be located within the StorageGRID system.
a|
link:olst-system-detected-lost-object.html[OLST: System Detected Lost Object]
a|
ORLM
a|
Object Rules Met: Object data is stored as specified by the ILM rules.
a|
link:orlm-object-rules-met.html[ORLM: Object Rules Met]
a|
SADD
a|
Security Audit Disable: Audit message logging was turned off.
a|
link:sadd-security-audit-disable.html[SADD: Security Audit Disable]
a|
SADE
a|
Security Audit Enable: Audit message logging has been restored.
a|
link:sade-security-audit-enable.html[SADE: Security Audit Enable]
a|
SVRF
a|
Object Store Verify Fail: A content block failed verification checks.
a|
link:svrf-object-store-verify-fail.html[SVRF: Object Store Verify Fail]
a|
SVRU
a|
Object Store Verify Unknown: Unexpected object data detected in the object store.
a|
link:svru-object-store-verify-unknown.html[SVRU: Object Store Verify Unknown]
a|
SYSD
a|
Node Stop: A shutdown was requested.
a|
link:sysd-node-stop.html[SYSD: Node Stop]
a|
SYST
a|
Node Stopping: A service initiated a graceful stop.
a|
link:syst-node-stopping.html[SYST: Node Stopping]
a|
SYSU
a|
Node Start: A service started; the nature of the previous shutdown is indicated in the message.
a|
link:sysu-node-start.html[SYSU: Node Start]
a|
VLST
a|
User Initiated Volume Lost: The `/proc/CMSI/Volume_Lost` command was run.
a|
link:vlst-user-initiated-volume-lost.html[VLST: User Initiated Volume Lost]
|===

.Related information

link:lkcu-overwritten-object-cleanup.html[LKCU: Overwritten Object Cleanup]
