settings:
  name: "StorageGRID 11.5"
  internal:
    pdf_enabled: false
  prod:
  # Keep PDF and localization off for initial publishing - bmegan
    pdf_enabled: false
    harmony_enabled: false
sidebar:
  entries:
    - title: StorageGRID 11.5 Docs
      url: /index.html
    - section: release-notes
    - title: Get started
      entries:
      - section: primer
      - section: network
    - title: Install and upgrade software
      entries:
      - section: rhel
      - section: ubuntu
      - section: vmware
      - section: upgrade
     - title: Install and maintain hardware
      entries:
      - section: sg6000
      - section: sg5700
      - section: sg5600
      - section: sg100-1000
    - title: Configure and manage
      entries:  
      - section: admin
      - section: ilm
      - section: harden
      - section: fabricpool
    - title: Use StorageGRID
      entries: 
      - section: tenant
      - section: s3
      - section: swift
    - title: Monitor and troubleshoot
      entries:  
      - section: monitor  
      - section: troubleshoot
      - section: audit
    - title: Maintain
      entries:
      - section: expand
      - section: maintain
    - title: Earlier versions
      url: /earlier-versions.html
    - title: Legal notices
      url: /legal-notices.html 

homepage:
  tiles:
    - title: Get started
      links:
      - title: Release notes
        url: /release-notes/index.html
      - title: What's new
        url: /upgrade/whats-new.html
      - title: Learn about StorageGRID
        url: /primer/index.html
      - title: Networking guidelines
        url: /network/index.html
      - title: Install & maintain hardware
      links:
      - title: SG6000 storage appliance
        url: /sg6000/index.html
      - title: SG5700 storage appliance
        url: /sg5700/index.html
      - title: SG5600 storage appliance
        url: /sg5600/index.html
      - title: SG100 and SG1000 services appliances
        url: /sg100-1000/index.html
     - title: Install & upgrade software
      links:
      - title: Install Red Hat Enterprise Linux or CentOS
        url: /rhel/index.html
      - title: Install Ubuntu or Debian
        url: /ubuntu/index.html
      - title: Install VMware
        url: /vmware/index.html
      - title: Upgrade software
        url: /upgrade/index.html
    - title: Configure the grid
      links:
      - title: Administer StorageGRID
        url: /admin/index.html
      - title: Manage objects with ILM
        url: /ilm/index.html
      - title: System hardening
        url: /harden/index.html
      - title: Configure StorageGRID for FabricPool
        url: /fabricpool/index.html
    - title: Manage objects
      links:
      - title: Use a tenant account
        url: /tenant/index.html
      - title: Use S3 REST API
        url: /s3/index.html
      - title: Use Swift REST API
        url: /swift/index.html
    - title: Monitor and maintain
      links:
      - title: Monitor
        url: /monitor/index.html
      - title: Troubleshoot
        url: /troubleshoot/index.html
      - title: Review audit logs
        url: /audit/index.html
      - title: Expand your grid
        url: /expand/index.html
      - title: Recover and maintain
        url: /maintain/index.html
    - title: Demos & tutorials
      links:
      - title: Learn how to enable StorageGRID
        url: https://docs.netapp.com/us-en/storagegrid-enable/index.html      
      - title: StorageGRID video library
        url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7nh2wGRA65iulXhtXwLiqrY
      - title: NetApp learning services
        url: https://www.netapp.com/support-and-training/netapp-university/
    - title: More resources
      links:
      - title: StorageGRID support page
        url: https://mysupport.netapp.com/site/products/all/details/5d9f1107e01d9c0001ee50f6/downloads-tab
      - title: NetApp Interoperability Matrix Tool (IMT)
        url: https://imt.netapp.com/matrix/#welcome
      - title: StorageGRID knowledge base
        url: https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID
      - title: NetApp blog
        url: https://netapp.com/blog/
      - title: NetApp community
        url: https://community.netapp.com/
    - title: Earlier versions
      links:
      - title: StorageGRID 11.4 documentation
        url: https://docs.netapp.com/sgws-114/index.jsp
      - title: StorageGRID 11.3 documentation
        url: https://docs.netapp.com/sgws-113/index.jsp