---
permalink: sg100-1000/configuring-bmc-interface-sg1000.html
sidebar: sidebar
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, BMC, baseboard management controller, configure, setup, set up
summary: 'The user interface for the baseboard management controller \(BMC\) on the services appliance provides status information about the hardware and allows you to configure SNMP settings and other options for the services appliance.'
---
= Configuring the BMC interface
:icons: font
:imagesdir: ../media/

[.lead]
The user interface for the baseboard management controller (BMC) on the services appliance provides status information about the hardware and allows you to configure SNMP settings and other options for the services appliance.

.Steps

* link:changing-root-password-for-bmc-interface-sg1000.html[Changing the root password for the BMC interface]
* link:setting-ip-address-for-bmc-management-port-sg1000.html[Setting the IP address for the BMC management port]
* link:accessing-bmc-interface-sg1000.html[Accessing the BMC interface]
* link:configuring-snmp-settings-for-sg1000.html[Configuring SNMP settings for the services appliance]
* link:setting-up-email-notifications-for-alerts.html[Setting up email notifications for alerts]
