---
permalink: sg100-1000/configuring-storagegrid-connections-sg100-and-sg1000.html
sidebar: sidebar
keywords: storagegrid, sg100, sg1000, service appliance, services appliance, gateway Node, admin node, storagegrid connections, connections, configure, setup, set up
summary: 'Before you can deploy the services appliance as a node in a StorageGRID system, you must configure the connections between the appliance and the networks you plan to use. You can configure networking by browsing to the StorageGRID Appliance Installer, which is pre-installed on the services appliance.'
---
= Configuring StorageGRID connections
:icons: font
:imagesdir: ../media/

[.lead]
Before you can deploy the services appliance as a node in a StorageGRID system, you must configure the connections between the appliance and the networks you plan to use. You can configure networking by browsing to the StorageGRID Appliance Installer, which is pre-installed on the services appliance.

.Steps

* link:accessing-storagegrid-appliance-installer-sg100-and-sg1000.html[Accessing the StorageGRID Appliance Installer]
* link:verifying-and-upgrading-storagegrid-appliance-installer-version.html[Verifying and upgrading the StorageGRID Appliance Installer version]
* link:configuring-network-links-sg100-and-sg1000.html[Configuring network links (SG100 and SG1000)]
* link:configuring-storagegrid-ip-addresses-sg100-and-sg1000.html[Configuring StorageGRID IP addresses]
* link:verifying-network-connections.html[Verifying network connections]
* link:verifying-port-level-network-connections.html[Verifying port-level network connections]
