---
permalink: ubuntu/deploying-virtual-grid-nodes.html
sidebar: sidebar
keywords: storagegrid, deploying grid nodes, deploy grid nodes, ubuntu, debian
summary: 'When you deploy grid nodes in an Ubuntu or Debian environment, you create node configuration files for all nodes, validate the files, and start the StorageGRID host service, which starts the nodes. If you need to deploy any StorageGRID appliance Storage Nodes, see the installation and maintenance instructions for the appliance after you have deployed all virtual nodes.'
---
= Deploying virtual grid nodes
:icons: font
:imagesdir: ../media/

[.lead]
When you deploy grid nodes in an Ubuntu or Debian environment, you create node configuration files for all nodes, validate the files, and start the StorageGRID host service, which starts the nodes. If you need to deploy any StorageGRID appliance Storage Nodes, see the installation and maintenance instructions for the appliance after you have deployed all virtual nodes.

* link:creating-node-configuration-files.html[Creating node configuration files]
* link:validating-storagegrid-configuration.html[Validating the StorageGRID configuration]
* link:starting-storagegrid-host-service.html[Starting the StorageGRID host service]

.Related information

link:../sg100-1000/index.html[SG100 & SG1000 services appliances]

link:../sg5600/index.html[SG5600 storage appliances]

link:../sg5700/index.html[SG5700 storage appliances]

link:../sg6000/index.html[SG6000 storage appliances]
