---
permalink: network/post-installation-guidelines.html
sidebar: sidebar
keywords:
summary: 'After completing grid node deployment and configuration, follow these guidelines for DHCP addressing and network configuration changes.'
---
= Post-installation guidelines
:icons: font
:imagesdir: ../media/

[.lead]
After completing grid node deployment and configuration, follow these guidelines for DHCP addressing and network configuration changes.

* If DHCP was used to assign IP addresses, configure a DHCP reservation for each IP address on the networks being used.
+
You can only set up DHCP during the deployment phase. You cannot set up DHCP during configuration.
+
IMPORTANT: Nodes reboot when their IP addresses change, which can cause outages if a DHCP address change affects multiple nodes at the same time.

* You must use the Change IP procedures if you want to change IP addresses, subnet masks, and default gateways for a grid node. See the information about configuring IP addresses in the recovery and maintenance instructions.
* If you make networking configuration changes, including routing and gateway changes, client connectivity to the primary Admin Node and other grid nodes might be lost. Depending on the networking changes applied, you might need to re-establish these connections.

.Related information

link:../rhel/index.html[Install Red Hat Enterprise Linux or CentOS]

link:../ubuntu/index.html[Install Ubuntu or Debian]

link:../vmware/index.html[Install VMware]

link:../sg100-1000/index.html[SG100 & SG1000 services appliances]

link:../sg6000/index.html[SG6000 storage appliances]

link:../sg5700/index.html[SG5700 storage appliances]

link:../sg5600/index.html[SG5600 storage appliances]

link:../maintain/index.html[Maintain & recover]
