---
permalink: network/storagegrid-networking-overview.html
sidebar: sidebar
keywords: storagegrid, network, networking, ethernet, subnet, routing
summary: 'Configuring the networking for a StorageGRID system requires a high level of experience with Ethernet switching, TCP/IP networking, subnets, network routing, and firewalls.'
---
= StorageGRID networking overview
:icons: font
:imagesdir: ../media/

[.lead]
Configuring the networking for a StorageGRID system requires a high level of experience with Ethernet switching, TCP/IP networking, subnets, network routing, and firewalls.

Before you configure networking, become familiar with StorageGRID architecture as described in the _Grid primer_.

Before you deploy and configure StorageGRID, you must configure the networking infrastructure. Communication needs to occur among all the nodes in the grid and between the grid and external clients and services.

External clients and external services need to connect to StorageGRID networks to perform functions such as the following:

* Store and retrieve object data
* Receive email notifications
* Access the StorageGRID management interface (the Grid Manager and Tenant Manager)
* Access the audit share (optional)
* Provide services such as:
 ** Network Time Protocol (NTP)
 ** Domain Name System (DNS)
 ** Key Management Server (KMS)

StorageGRID networking must be configured appropriately to handle the traffic for these functions and more.

After you determine which of the three StorageGRID networks you want to use and how those networks will be configured, you can install and configure the StorageGRID nodes by following the appropriate instructions.

.Related information

link:../primer/index.html[Grid primer]

link:../admin/index.html[Administer StorageGRID]

link:../release-notes/index.html[Release notes]

link:../rhel/index.html[Install Red Hat Enterprise Linux or CentOS]

link:../ubuntu/index.html[Install Ubuntu or Debian]

link:../vmware/index.html[Install VMware]

link:../sg100-1000/index.html[SG100 & SG1000 services appliances]

link:../sg6000/index.html[SG6000 storage appliances]

link:../sg5700/index.html[SG5700 storage appliances]

link:../sg5600/index.html[SG5600 storage appliances]
