---
permalink: sg5600/configuring-hardware.html
sidebar: sidebar
keywords: storagegrid, sg5600, storage node, storage appliance, hardware, configure, configuration, set up, setup, network, networking
summary: 'After applying power to the appliance, you must configure SANtricity Storage Manager, which is the software you will use to monitor the hardware. You must also configure the network connections that will be used by StorageGRID.'
---
= Configuring the hardware
:icons: font
:imagesdir: ../media/

[.lead]
After applying power to the appliance, you must configure SANtricity Storage Manager, which is the software you will use to monitor the hardware. You must also configure the network connections that will be used by StorageGRID.

.Steps

* link:configuring-storagegrid-connections.html[Configuring StorageGRID connections]
* link:configuring-santricity-storage-manager.html[Configuring SANtricity Storage Manager]
* link:optional-enabling-node-encryption.html[Optional: Enabling node encryption]
* link:optional-changing-to-raid6-mode-sg5660-only.html[Optional: Changing to RAID6 mode (SG5660 only)]
* link:optional-remapping-network-ports-for-appliance-sg5600-and-sg5700.html[Optional: Remapping network ports for the appliance]
