---
permalink: sg5600/preparing-for-installation.html
sidebar: sidebar
keywords: storagegrid, sg5600, storage node, storage appliance, install, installation, preparation, get ready, prepare
summary: 'Preparing to install a StorageGRID appliance entails preparing the site and obtaining all required hardware, cables, and tools. You should also gather IP addresses and network information.'
---
= Preparing for installation
:icons: font
:imagesdir: ../media/

[.lead]
Preparing to install a StorageGRID appliance entails preparing the site and obtaining all required hardware, cables, and tools. You should also gather IP addresses and network information.

.Steps

* link:preparing-site-sg5600.html[Preparing the site (SG5600)]
* link:unpacking-boxes-sg5600.html[Unpacking the boxes (SG5600)]
* link:obtaining-additional-equipment-and-tools-sg5600.html[Obtaining additional equipment and tools (SG5600)]
* link:service-laptop-requirements-sg5600.html[Service laptop requirements]
* link:web-browser-requirements.html[Web browser requirements]
* link:reviewing-appliance-network-connections-sg5600.html[Reviewing appliance network connections]
* link:gathering-installation-information-sg5600.html[Gathering installation information (SG5600)]
