---
permalink: tenant/managing-s3-platform-services.html
sidebar: sidebar
keywords:
summary: 'If the use of platform services is allowed for your S3 tenant account, you can use platform services to leverage external services and configure CloudMirror replication, notifications, and search integration for S3 buckets.'
---
= Managing S3 platform services
:icons: font
:imagesdir: ../media/

[.lead]
If the use of platform services is allowed for your S3 tenant account, you can use platform services to leverage external services and configure CloudMirror replication, notifications, and search integration for S3 buckets.

* link:what-platform-services-are.html[What platform services are]

* link:considerations-for-using-platform-services.html[Considerations for using platform services]

* link:configuring-platform-services-endpoints.html[Configuring platform services endpoints]

* link:configuring-cloudmirror-replication.html[Configuring CloudMirror replication]

* link:configuring-event-notifications.html[Configuring event notifications]

* link:using-search-integration-service.html[Using the search integration service]
