---
permalink: vmware/deploying-virtual-machine-grid-nodes-in-vmware-vsphere-web-client.html
sidebar: sidebar
keywords: storagegrid, deploying grid nodes, deploy grid nodes, vsphere, vsphere web client
summary: 'You use VMware vSphere Web Client to deploy each grid node as a virtual machine. During deployment, each grid node is created and connected to one or more networks. If you need to deploy any StorageGRID appliance Storage Nodes, see the installation and maintenance instructions for the appliance after you have deployed all virtual machine grid nodes.'
---
= Deploying virtual machine grid nodes in VMware vSphere Web Client
:icons: font
:imagesdir: ../media/

[.lead]
You use VMware vSphere Web Client to deploy each grid node as a virtual machine. During deployment, each grid node is created and connected to one or more networks. If you need to deploy any StorageGRID appliance Storage Nodes, see the installation and maintenance instructions for the appliance after you have deployed all virtual machine grid nodes.

* link:collecting-information-about-your-deployment-environment.html[Collecting information about your deployment environment]
* link:how-grid-nodes-discover-primary-admin-node.html[How grid nodes discover the primary Admin Node]
* link:deploying-storagegrid-node-as-virtual-machine.html[Deploying a StorageGRID node as a virtual machine]

.Related information

link:../sg100-1000/index.html[SG100 & SG1000 services appliances]

link:../sg5600/index.html[SG5600 storage appliances]

link:../sg5700/index.html[SG5700 storage appliances]

link:../sg6000/index.html[SG6000 storage appliances]
