---
permalink: admin/configuring-archive-node-connections-to-archival-storage.html
sidebar: sidebar
keywords:
summary: 'When you configure an Archive Node to connect with an external archive, you must select the target type.'
---
= Configuring Archive Node connections to archival storage
:icons: font
:imagesdir: ../media/

[.lead]
When you configure an Archive Node to connect with an external archive, you must select the target type.

The StorageGRID system supports the archiving of object data to the cloud through an S3 interface or to tape through Tivoli Storage Manager (TSM) middleware.

NOTE: Once the type of archival target is configured for an Archive Node, the target type cannot be changed.

* link:archiving-to-cloud-through-s3-api.html[Archiving to the cloud through the S3 API]
* link:archiving-to-tape-through-tsm-middleware.html[Archiving to tape trough TSM middleware]
* link:configuring-archive-node-retrieve-settings.html[Configuring Archive Node retrieve settings]
* link:configuring-archive-node-replication.html[Configuring Archive Node replication]
