---
permalink: admin/configuring-sso.html
sidebar: sidebar
keywords:
summary: 'When single sign-on \(SSO\) is enabled, users can only access the Grid Manager, the Tenant Manager, the Grid Management API, or the Tenant Management API if their credentials are authorized using the SSO sign-in process implemented by your organization.'
---
= Configuring single sign-on
:icons: font
:imagesdir: ../media/

[.lead]
When single sign-on (SSO) is enabled, users can only access the Grid Manager, the Tenant Manager, the Grid Management API, or the Tenant Management API if their credentials are authorized using the SSO sign-in process implemented by your organization.

* link:confirming-federated-users-can-sign-in.html[Confirming federated users can sign in]
* link:using-sandbox-mode.html[Using sandbox mode]
* link:creating-relying-party-trusts-in-ad-fs.html[Creating relying party trusts in AD FS]
* link:testing-relying-party-trusts.html[Testing relying party trusts]
* link:enabling-single-sign-on.html[Enabling single sign-on]
* link:disabling-single-sign-on.html[Disabling single sign-on]
* link:temporarily-disabling-and-reenabling-sso-for-admin-node.html[Temporarily disabling and reenabling single sign-on for one Admin Node]
