---
permalink: admin/controlling-administrator-access-to-storagegrid.html
sidebar: sidebar
keywords:
summary: 'You can control administrator access to the StorageGRID system by opening or closing firewall ports, managing admin groups and users, configuring single sign-on \(SSO\), and providing client certificates to allow secure external access to StorageGRID metrics.'
---
= Controlling administrator access to StorageGRID
:icons: font
:imagesdir: ../media/

[.lead]
You can control administrator access to the StorageGRID system by opening or closing firewall ports, managing admin groups and users, configuring single sign-on (SSO), and providing client certificates to allow secure external access to StorageGRID metrics.

* link:controlling-access-through-firewalls.html[Controlling access through firewalls]
* link:using-identity-federation.html[Using identity federation]
* link:managing-admin-groups.html[Managing admin groups]
* link:managing-local-users.html[Managing local users]
* link:using-single-sign-on.html[Using single sign-on (SSO) for StorageGRID]
* link:configuring-administrator-client-certificates.html[Configuring administrator client certificates]
