---
permalink: admin/kms-adding.html
sidebar: sidebar
keywords:
summary: 'You use the StorageGRID Key Management Server wizard to add each KMS or KMS cluster.'
---
= Adding a key management server (KMS)
:icons: font
:imagesdir: ../media/

[.lead]
You use the StorageGRID Key Management Server wizard to add each KMS or KMS cluster.

.What you'll need

* You must have reviewed the link:kms-considerations-and-requirements.html[considerations and requirements for using a key management server].

* You must have link:kms-configuring-storagegrid-as-client.html[configured StorageGRID as a client in the KMS], and you must have the required information for each KMS or KMS cluster

* You must have the Root Access permission.
* You must be signed in to the Grid Manager using a supported browser.

.About this task

If possible, configure any site-specific key management servers before configuring a default KMS that applies to all sites not managed by another KMS. If you create the default KMS first, all node-encrypted appliances in the grid will be encrypted by the default KMS. If you want to create a site-specific KMS later, you must first copy the current version of the encryption key from the default KMS to the new KMS.

link:kms-considerations-for-changing-for-site.html[Considerations for changing the KMS for a site]

.Steps

. link:kms-adding-enter-kms-details.html[Step 1: Enter KMS Details]
. link:kms-adding-upload-server-certificate.html[Step 2: Upload Server Certificate]
. link:kms-adding-upload-client-certificates.html[Step 3: Upload Client Certificates]
