---
permalink: s3/s3-rest-api-supported-operations-and-limitations.html
sidebar: sidebar
keywords:
summary: ''
---
= S3 REST API supported operations and limitations
:icons: font
:imagesdir: ../media/

[.lead]
The StorageGRID system implements the Simple Storage Service API (API Version 2006-03-01) with support for most operations, and with some limitations. You need to understand the implementation details when you are integrating S3 REST API client applications.

The StorageGRID system supports both virtual hosted-style requests and path-style requests.

* link:authenticating-requests.html[Authenticating requests]
* link:operations-on-the-service.html[Operations on the service]
* link:operations-on-buckets.html[Operations on buckets]
* link:custom-operations-on-buckets.html[Custom operations on buckets]
* link:operations-on-objects.html[Operations on objects]
* link:operations-for-multipart-uploads.html[Operations for multipart uploads]
* link:error-responses.html[Error responses]

== Date handling
The StorageGRID implementation of the S3 REST API only supports valid HTTP date formats.

The StorageGRID system only supports valid HTTP date formats for any headers that accept date values. The time portion of the date can be specified in Greenwich Mean Time (GMT) format, or in Universal Coordinated Time (UTC) format with no time zone offset (+0000 must be specified). If you include the `x-amz-date` header in your request, it overrides any value specified in the Date request header. When using AWS Signature Version 4, the `x-amz-date` header must be present in the signed request because the date header is not supported.

== Common request headers
The StorageGRID system supports common request headers defined by the _Simple Storage Service API Reference_, with one exception.

[options="header"]
|===
| Request header| Implementation
a|
Authorization
a|
Full support for AWS Signature Version 2

Support for AWS Signature Version 4, with the following exceptions:

* The SHA256 value is not calculated for the body of the request. The user-submitted value is accepted without validation, as if the value `UNSIGNED-PAYLOAD` had been provided for the `x-amz-content-sha256` header.

a|
x-amz-security-token
a|
Not implemented. Returns `XNotImplemented`.
|===

== Common response headers
The StorageGRID system supports all of the common response headers defined by the _Simple Storage Service API Reference_, with one exception.

[options="header"]
|===
| Response header| Implementation
a|
x-amz-id-2
a|
Not used
|===
.Related information

http://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html[Amazon Web Services (AWS) Documentation: Amazon Simple Storage Service API Reference]
