---
permalink: maintain/storagegrid-hotfix-procedure.html
sidebar: sidebar
keywords:
summary: 'You might need to apply a hotfix to your StorageGRID system if issues with the software are detected and resolved between feature releases.'
---
= StorageGRID hotfix procedure
:icons: font
:imagesdir: ../media/

[.lead]
You might need to apply a hotfix to your StorageGRID system if issues with the software are detected and resolved between feature releases.

StorageGRID hotfixes contain software changes that are made available outside of a feature or patch release. The same changes are included in a future release. In addition, each hotfix release contains a roll-up of all previous hotfixes within the feature or patch release.

* link:considerations-for-applying-hotfix.html[Considerations for applying a hotfix]

* link:how-your-system-is-affected-when-you-apply-hotfix.html[How your system is affected when you apply a hotfix]

* link:obtaining-required-materials-for-hotfix.html[Obtaining the required materials for a hotfix]

* link:downloading-hotfix-file.html[Downloading the hotfix file]

* link:checking-systems-condition-before-applying-hotfix.html[Checking the system's condition before applying a hotfix]

* link:applying-hotfix.html[Applying the hotfix]
