---
permalink: primer/using-storagegrid.html
sidebar: sidebar
keywords:
summary: 'After you install grid nodes and StorageGRID networks, you can begin to configure and use StorageGRID. Some of the tasks you will perform include controlling user access to system administration functions, setting up tenant accounts , managing client connections, setting configuration options, managing object locations with ILM, monitoring the health and day-to-day activities of your StorageGRID system, and performing routine and non-routine maintenance activities.'
---
= Using StorageGRID
:icons: font
:imagesdir: ../media/

[.lead]
After you install grid nodes and StorageGRID networks, you can begin to configure and use StorageGRID. Some of the tasks you will perform include controlling user access to system administration functions, setting up tenant accounts , managing client connections, setting configuration options, managing object locations with ILM, monitoring the health and day-to-day activities of your StorageGRID system, and performing routine and non-routine maintenance activities.

* xref:controlling-storagegrid-access.adoc[Controlling StorageGRID access]
* xref:managing-tenants-and-client-connections.adoc[Managing tenants and client connections]
* xref:configuring-network-settings.adoc[Configuring network settings]
* xref:configuring-system-settings.adoc[Configuring system settings]
* xref:using-information-lifecycle-management.adoc[Using information lifecycle management]
* xref:monitoring-storagegrid-operations.adoc[Monitoring StorageGRID operations]
* xref:performing-maintenance-procedures.adoc[Performing maintenance procedures]
* xref:using-storagegrid-support-options.adoc[Using StorageGRID support options]
